name: Java - build and test

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/build-java.yml'

jobs:
  build-and-test-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'
          cache: 'maven'

      - name: Build and test / Maven
        run: ./mvnw -B clean package
